# Generated by Django 6.0.5 on 2026-06-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='amenities',
        ),
    ]
