# Generated by Django 6.0.5 on 2026-06-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_remove_venue_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='amenities',
            field=models.ManyToManyField(related_name='venues', to='venue.amenity'),
        ),
    ]
