# Generated by Django 6.0.5 on 2026-06-20 19:11

import django.core.validators
import django.db.models.deletion
import venue.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_venue_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueavailability',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueavailability',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Mark this day as fully closed (holiday/off day).'),
        ),
        migrations.AlterField(
            model_name='venueavailability',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueavailability',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='venue.venue'),
        ),
        migrations.AlterField(
            model_name='venueimage',
            name='image',
            field=models.ImageField(upload_to=venue.utils.venue_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
