# Generated by Django 6.0.5 on 2026-06-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_venueownerprofile_options_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpverification',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP Verification', 'verbose_name_plural': 'OTP Verifications'},
        ),
        migrations.AlterModelOptions(
            name='venueownerprofile',
            options={'verbose_name': 'Venue Owner Profile', 'verbose_name_plural': 'Venue Owner Profiles'},
        ),
    ]
