# Generated by Django 6.0.5 on 2026-06-09 14:07

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_venueownerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venueownerprofile',
            options={'verbose_name': 'Venue Owner Profile', 'verbose_name_plural': 'Venue Owner Profiles'},
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number in E.164 format (e.g. +447700900123).', regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('venue_owner', 'Venue Owner'), ('admin', 'Admin')], max_length=20),
        ),
    ]
