# Generated by Django 6.0.5 on 2026-06-09 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_venueownerprofile_options_user_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verified',
            new_name='is_email_verified',
        ),
        migrations.RenameField(
            model_name='venueownerprofile',
            old_name='is_verified',
            new_name='is_profile_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number in E.164 format (e.g. +447700900123).', regex='^\\+[1-9]\\d{7,14}$')]),
        ),
    ]
