# Generated by Django 6.0.5 on 2026-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otpverification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'otp_type', 'is_used'], name='accounts_ot_user_id_949a16_idx'),
        ),
    ]
